language: java
jdk: oraclejdk8
sudo: false
install: true

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

addons:
  sonarqube:
    organization: cast-github
    token:
      secure: "npRD3LiHE+M68OFFbebPqdJcYoZwCxvrHk+r5ZbIo88CxpuddDCNWh8sAlMrkgiIiO6Fh+cFab8iwVfW88DTU0i1+Fe+jN7Eq3/xxxoDwL2zKtCzMt0Q68BpwPgVTkfjIwcf+8m6fYNqv191d2qXwswMQI8GiO5ucSegC2posBQlGtSluiD7SlLSwpw5wpItELcvut7SOsl/HicCZfjS3uXsZXlOdmq/TLY25TFnXvZdSChashOX387g2Y44/CCohR9OUacKebH7wcvYhoFfxhj2US5DdUkvJimu0lTUZxX6lIzFHCOtWViGo+FBA1PTQfzARQZaXD3wK7QItbG+jHWuk+2kP2jBblZD2PLjVRS1kCaI3Oj2NfxCOw1puI4TRgnXF8lmQv4i1aEqNpwQNyXuJ1Zx+GOlRlBUzmswkYD2JVf1vZ9MXBmSmCCB7tn9JtZKrjcrgCZqChJXVWhtCtxZ68A35GFCdpjVvfgU64NH/BBDKZiYBF6iLr5+D8QBZVyXW/JG6QkEfylUuLFoBJ/1rLKNkU4/TXjCatuo/+87GPZpdTnrXlr7y1NCINa/Z6FWMlAlBf4ZoYNERMll17cITDEKeCK9LLL5c1SdLYJyqOZOtiBN3STHT6bTcSOb8Wsw39E477WbOpnw/wZQJh5C4koZUw+VTA/876oQZAo="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
